# Site Settings
baseurl: ""
url: "https:/ollys.work"

# Blog Settings
theme_settings:
  title: Olly Pethick
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/profilephoto.jpeg
    username: Olly Pethick
    description: Frontend Web Developer
    experience:
      - start: 2022-12-05
        end: Present
        experience: abrdn, React Developer
      - start: 2021-11-01
        end: 2022-11-18
        experience: Kwalee, Frontend Web Developer

      - start: 2019-09-01
        end: 2021-11-01
        experience: Kwalee, Junior Frontend Web Developer

      - start: 2017-07-03
        end: 2019-07-04
        experience: Colligiate Church of St Mary, Warwick, Web Developer

      - start: 2017-03-03
        end: 2019-03-06
        experience: Loughborough Student's Union, eLearning Developer
    education:
      - start: 2016-09-01
        end: 2019-06-01
        experience: Loughborough University, Computer Science, 1st Class Honours

      - start: 2011-09-01
        end: 2013-06-01
        experience: King Edward VI Grammer School, A-Levels

      - start: 2008-09-01
        end: 2011-06-01
        experience: Princethorpe College, GSCEs
    skills:
      - skill: React
      - skill: Redux Toolkit
      - skill: JavaScript
      - skill: TypeScript
      - skill: Next.js
      - skill: Gatsby
      - skill: React Native
      - skill: HTML5
      - skill: CSS
      - skill: SASS
      - skill: Less
      - skill: Git
      - skill: Jekyll
      - skill: Wordpress
      - skill: Docker
      - skill: npm
      - skill: Node.js
      - skill: Express
    achievements:
      - achievement: LEN Enterprising Society of the Year 2018
      - achievement: Oxford Hack - Prize Winner
      - achievement: Warwick Hack - Prize Winner
      - achievement: Violin - Grade 5
      - achievement: RSC Music Award - Silver

  # Icons
  icons:
    email: ollypethick@gmail.com
    linkedin: https://www.linkedin.com/in/ollypethick/
    github: ollypolly
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    cv: https://drive.google.com/file/d/1PIT45-oSgB05l908WjL5bXLJTVbdsa5S/view?usp=sharing
  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
