# Site Settings
baseurl: ""
url: "https:/olly.works"

# Blog Settings
theme_settings:
  title: Olly Pethick
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/profilephoto.jpeg
    username: Olly Pethick
    description: Frontend Web Developer
    experience:
      - start: 2019-09-01
        end: Present
        experience: Kwalee, Frontend Web Developer

      - start: 2017-07-03
        end: 2019-07-04
        experience: Colligiate Church of St Mary's Warwick, Technical Advisor

      - start: 2017-03-03
        end: 2019-03-06
        experience: Loughborough Student's Union, eLearning Developer
    skills:
      - skill: React
        value: 85 # Percent value
      - skill: Redux
        value: 85 # Percent value
      - skill: Typescript
        value: 85 # Percent value
      - skill: Next.js
        value: 65 # Percent value
      - skill: React Native
        value: 65 # Percent value

  # Icons
  icons:
    email: ollypethick@gmail.com
    linkedin: https://www.linkedin.com/in/ollypethick/
    github: ollypolly
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    cv: https://drive.google.com/file/d/1W24GQMa8EUGLAcFVtEizHe-unZhFP47E/view?usp=sharing

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
